Category.create!([
  {name: "Food"},
  {name: "Housing"},
  {name: "Transportation"},
  {name: "Shopping"},
  {name: "Activities"},
  {name: "Miscellaneous"}
])
Currency.create!([
  {code: "AED"},
  {code: "AFN"},
  {code: "ALL"},
  {code: "AMD"},
  {code: "ANG"},
  {code: "AOA"},
  {code: "ARS"},
  {code: "AUD"},
  {code: "AWG"},
  {code: "AZN"},
  {code: "BAM"},
  {code: "BBD"},
  {code: "BDT"},
  {code: "BGN"},
  {code: "BHD"},
  {code: "BIF"},
  {code: "BMD"},
  {code: "BND"},
  {code: "BOB"},
  {code: "BRL"},
  {code: "BSD"},
  {code: "BTC"},
  {code: "BTN"},
  {code: "BWP"},
  {code: "BYR"},
  {code: "BZD"},
  {code: "CAD"},
  {code: "CDF"},
  {code: "CHF"},
  {code: "CLF"},
  {code: "CLP"},
  {code: "CNY"},
  {code: "COP"},
  {code: "CRC"},
  {code: "CUP"},
  {code: "CVE"},
  {code: "CZK"},
  {code: "DJF"},
  {code: "DKK"},
  {code: "DOP"},
  {code: "DZD"},
  {code: "EEK"},
  {code: "EGP"},
  {code: "ERN"},
  {code: "ETB"},
  {code: "EUR"},
  {code: "FJD"},
  {code: "FKP"},
  {code: "GBP"},
  {code: "GEL"},
  {code: "GGP"},
  {code: "GHS"},
  {code: "GIP"},
  {code: "GMD"},
  {code: "GNF"},
  {code: "GTQ"},
  {code: "GYD"},
  {code: "HKD"},
  {code: "HNL"},
  {code: "HRK"},
  {code: "HTG"},
  {code: "HUF"},
  {code: "IDR"},
  {code: "ILS"},
  {code: "IMP"},
  {code: "INR"},
  {code: "IQD"},
  {code: "IRR"},
  {code: "ISK"},
  {code: "JEP"},
  {code: "JMD"},
  {code: "JOD"},
  {code: "JPY"},
  {code: "KES"},
  {code: "KGS"},
  {code: "KHR"},
  {code: "KMF"},
  {code: "KPW"},
  {code: "KRW"},
  {code: "KWD"},
  {code: "KYD"},
  {code: "KZT"},
  {code: "LAK"},
  {code: "LBP"},
  {code: "LKR"},
  {code: "LRD"},
  {code: "LSL"},
  {code: "LTL"},
  {code: "LVL"},
  {code: "LYD"},
  {code: "MAD"},
  {code: "MDL"},
  {code: "MGA"},
  {code: "MKD"},
  {code: "MMK"},
  {code: "MNT"},
  {code: "MOP"},
  {code: "MRO"},
  {code: "MTL"},
  {code: "MUR"},
  {code: "MVR"},
  {code: "MWK"},
  {code: "MXN"},
  {code: "MYR"},
  {code: "MZN"},
  {code: "NAD"},
  {code: "NGN"},
  {code: "NIO"},
  {code: "NOK"},
  {code: "NPR"},
  {code: "NZD"},
  {code: "OMR"},
  {code: "PAB"},
  {code: "PEN"},
  {code: "PGK"},
  {code: "PHP"},
  {code: "PKR"},
  {code: "PLN"},
  {code: "PYG"},
  {code: "QAR"},
  {code: "RON"},
  {code: "RSD"},
  {code: "RUB"},
  {code: "RWF"},
  {code: "SAR"},
  {code: "SBD"},
  {code: "SCR"},
  {code: "SDG"},
  {code: "SEK"},
  {code: "SGD"},
  {code: "SHP"},
  {code: "SLL"},
  {code: "SOS"},
  {code: "SRD"},
  {code: "STD"},
  {code: "SVC"},
  {code: "SYP"},
  {code: "SZL"},
  {code: "THB"},
  {code: "TJS"},
  {code: "TMT"},
  {code: "TND"},
  {code: "TOP"},
  {code: "TRY"},
  {code: "TTD"},
  {code: "TWD"},
  {code: "TZS"},
  {code: "UAH"},
  {code: "UGX"},
  {code: "USD"},
  {code: "UYU"},
  {code: "UZS"},
  {code: "VEF"},
  {code: "VND"},
  {code: "VUV"},
  {code: "WST"},
  {code: "XAF"},
  {code: "XAG"},
  {code: "XAU"},
  {code: "XCD"},
  {code: "XDR"},
  {code: "XOF"},
  {code: "XPF"},
  {code: "YER"},
  {code: "ZAR"},
  {code: "ZMK"},
  {code: "ZMW"},
  {code: "ZWL"}
])

Location.create!([
  {name: "Houston TX USA"},
  {name: "Austin TX USA"},
  {name: "Dallas TX USA"},
  {name: "Washington DC USA"},
  {name: "Charleston SC USA"},
  {name: "New York NY USA"},
  {name: "Miami FL USA"},
  {name: "Paris France"},
  {name: "London England"},
  {name: "Rome Italy"},
  {name: "Prague Czechoslovakia"},
  {name: "Auckland New Zealand"},
  {name: "Leeds England"},
  {name: "Edinborough Scotland"},
  {name: "Oahu HI USA"},
  {name: "Strassbourg France"},
  {name: "Hong Kong"},
  {name: "New York, NY, United States"},
  {name: "Rome, Italy"},
  {name: "London, United Kingdom"},
  {name: "Nice, France"},
  {name: "Paris, France"},
  {name: "Las Vegas, NV, United States"},
  {name: "São Paulo, Brazil"}
])

User.create!([
  {username: "michelle", password_digest: "$2a$10$Aw1r32yDZQ47.Pwhtm/q7uwentD1uYknvP4Jv/P1ldgf62Ugmw8eO", email: "michelle@gmail.com", first_name: "Michelle", last_name: "Chu"},
  {username: "sarah", password_digest: "$2a$10$QbyQjWgOu/LzeonSXe.3nOxBFG3sTKvJseOdaN1W9TIMy/YjRnvF6", email: "sarah@gmail.com", first_name: "Sarah", last_name: "Taurchini"},
  {username: "nicolle", password_digest: "$2a$10$qTsvRPyECh1qxbx55kmSsONhYTsocbr4AVkL42IIJSGbrUCXtSIlO", email: "nicolle@gmail.com", first_name: "Nicolle", last_name: "Quintero"}
])
Trip.create!([
  {user_id: 3, name: "Euro-Trip", description: "Two week trip through England, Italy and France", budget: 2000, is_published: false, is_private: false},
  {user_id: 3, name: "Big Apple Visit", description: "Finally got to visit the best city in the world!", budget: 1000, is_published: false, is_private: false},
  {user_id: 3, name: "Party Time in Vegas", description: "What to do in sin city", budget: 100, is_published: false, is_private: false},
  {user_id: 3, name: "Brazil Adventures", description: "A 3-city tour of Brazil", budget: 1000, is_published: false, is_private: false}
])
Expense.create!([
  {location_id: 20, cost: 19.0, title: "Duck Tour", description: "Awesome 75 minute trip around the major spots in London. I'd recommend you take this tour during the first day or so of your stay so you have an idea of where you'd like to spend more time. Be sure to book 5-7 days in advance.", category_id: 5, date: nil, currency_id: 49, usd_cost: 30.7, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 20, cost: 0.0, title: "Westminster Abbey", description: "Beautiful architecture. Tours are free and include the Big Ben and Houses of Parliament. You can even catch a worship service on Sundays. Don't miss this!", category_id: 5, date: nil, currency_id: 49, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 20, cost: 0.0, title: "Buckingham Palace", description: "Official residence of Britain's sovereigns since 1837. Free sightseeing, tours only during the summer months.", category_id: 5, date: nil, currency_id: 49, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 20, cost: 0.0, title: "St James's Park", description: "Charming and romantic gardens. Perfect for a picnic or a leisurely stroll. Located near Buckingham Palace, so I'd recommend stopping by both during your trip.", category_id: 5, date: nil, currency_id: 49, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 20, cost: 14.0, title: "The London Eye", description: "Huge 135 metre high ferris wheel. The trip takes around 20 minutes, so be sure to bring your camera for beautiful panoramas of the city. The pods you take your trip on are standing room only. ", category_id: 5, date: nil, currency_id: 49, usd_cost: 22.62, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 19, cost: 10.0, title: "Collosseum", description: "It goes without saying this is a must do! Note that you can actually get in for free, but I'd recommend paying for a tour to save yourself from hours of waiting in line. Also consider buying a joint pass to visit Palatine Hill, which is also beautiful and can't be missed.", category_id: 5, date: nil, currency_id: 46, usd_cost: 12.8, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 19, cost: 0.0, title: " Pantheon", description: "Absolutely beautiful. Very crowded, as is to be expected but worth the hassle. Try to visit both during the day and nighttime as both offer stunning views and photo opps.", category_id: 5, date: nil, currency_id: 46, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 19, cost: 0.0, title: "Roman Forum", description: "Across the street from the Colosseum and a must-see for getting a glimpse into Roman life back in the day. I'd recommend getting the audio guide for a thorough history lesson.", category_id: 5, date: nil, currency_id: 46, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 21, cost: 30.0, title: "Nice Bike Tour", description: "Comprehensive bike tour that covers architectural, historical and cultural landmarks. Bike and helmet included, bring a light snack or grab one on the way.", category_id: 5, date: nil, currency_id: 46, usd_cost: 38.39, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 21, cost: 0.0, title: "Parfumerie Fragonard", description: "Behind the scenes tour of a perfume factory. Came across this by accident and was pleasantly surprised. Their fragrances smell great and last a long time, I'd recommend grabbing at least the smaller-sizes for a gift.", category_id: 5, date: nil, currency_id: 150, usd_cost: 0.0, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 22, cost: 17.0, title: "Louvre", description: "You are pretty much obligated to visit this museum if anywhere near Paris. What an experience to see such beautiful and meaningful artwork in person. The Mona Lisa is smaller than you'd think! Be sure to grab an audio or in-person tour.", category_id: 5, date: nil, currency_id: 46, usd_cost: 21.75, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 22, cost: 60.0, title: "Fat Tire Bike Tour", description: "8 hour bike tour that is worth every penny. Great intro to the city, make note of places your want to take a deeper tour of. Includes a charming picnic. Very accommodating for riders of all ages and abilities.", category_id: 5, date: nil, currency_id: 46, usd_cost: 76.77, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 22, cost: 12.0, title: "Eiffel Tower", description: "Be sure to check it out at night during one of the hourly lightshows. Also take note that you can't visit the very top tier in the winter months.", category_id: 5, date: nil, currency_id: 46, usd_cost: 15.35, expensable_id: 1, expensable_type: "Trip"},
  {location_id: 18, cost: 0.0, title: "Central Park Zoo", description: "Just to set expectations, this is a fairly small zoo. If you have limited time I wouldn't put this at the top of your list but definitely take a stroll through Central Park even if you can't visit the zoo.", category_id: 5, date: nil, currency_id: 150, usd_cost: 0.0, expensable_id: 2, expensable_type: "Trip"},
  {location_id: 18, cost: 29.0, title: "Top of the Rock", description: "Wonderful views of the city. I'd highly recommend doing this over the Empire State building because the views are better (slightly closer to the buildings on account of it being a shorter building), and it has a great view of the ESB so you can actually take a photo with it instead of just on it.", category_id: 5, date: nil, currency_id: 150, usd_cost: 29.0, expensable_id: 2, expensable_type: "Trip"},
  {location_id: 18, cost: 40.0, title: "Red Rooster", description: "Southern fusion cuisine. A little over-hyped in my opinion, especially if you're a fried chicken connoisseur. Their midnight brunch on the other hand (served from 12:30am to 4am) is delicious and a great price.", category_id: 1, date: nil, currency_id: 150, usd_cost: 40.0, expensable_id: 2, expensable_type: "Trip"},
  {location_id: 23, cost: 0.0, title: "Bellagio Fountains", description: "Be sure to catch one of the shows they put on every 15 minutes - it's very beautiful and worth of a few photos. Once it's done head inside to see the beautiful lobby inside the Bellagio, especially during the winter when decorated for the holidays.", category_id: 5, date: nil, currency_id: 150, usd_cost: 0.0, expensable_id: 3, expensable_type: "Trip"},
  {location_id: 24, cost: 40.0, title: "Santo Grão", description: "Yummy restaurant, especially for Sunday brunches. Beware that São Paulo is pricy in general and this place is no different. Expect to spend a little extra on that bloody mary. ", category_id: 1, date: nil, currency_id: 20, usd_cost: 16.26, expensable_id: 4, expensable_type: "Trip"},
  {location_id: 24, cost: 40.0, title: "Braz Pizzaria", description: "Absolutely delicious pizza. In a city known for its pizza, this ranks at the very top. Be sure to try their specialty pizzas. The Paulistana is one of my favorite (Mozzarella, grated smoked cheese, sprinkled with chunks of fresh tomatoes and slivers of black olives).", category_id: 1, date: nil, currency_id: 20, usd_cost: 16.26, expensable_id: 4, expensable_type: "Trip"},
  {location_id: 24, cost: 0.0, title: "Ibirapuera Park", description: "Huge park in the middle of the city. Perfect for a stroll, job or game of pickup football (soccer). Grab the local treats sold by the vendors.", category_id: 5, date: nil, currency_id: 20, usd_cost: 0.0, expensable_id: 4, expensable_type: "Trip"},
  {location_id: 24, cost: 0.0, title: "Botanical Gardens Of Sao Paulo", description: "Nice quiet spot for picnics that is surprisingly free of large crowds. Take one of the classes offered on the lawn if you get a chance.", category_id: 5, date: nil, currency_id: 20, usd_cost: 0.0, expensable_id: 4, expensable_type: "Trip"},
  {location_id: 24, cost: 100.0, title: "Barbacoa Itaim", description: "Holy meet sweats! Be prepared to eat like a king or queen. The waiters circle around with slabs of delicious meat and you are guaranteed to eat until your belly hurts. Note that the Brazilian way is to eat meats first, then veggies after - there is a method to this madness.", category_id: 1, date: nil, currency_id: 20, usd_cost: 40.66, expensable_id: 4, expensable_type: "Trip"}
])

