mich = User.create(username:"michelle", password:"password", password_confirmation:"password", first_name:"Michelle", last_name:"Chu", email:"michelle@gmail.com")
sarah = User.create(username:"sarah", password:"password", password_confirmation:"password", first_name:"Sarah", last_name:"Taurchini", email:"sarah@gmail.com")
nic = User.create(username:"nicolle", password:"password", password_confirmation:"password", first_name:"Nicolle", last_name:"Quintero", email:"nicolle@gmail.com")

houston = Location.create(name:"Houston TX USA")
austin = Location.create(name:"Austin TX USA")
dallas = Location.create(name:"Dallas TX USA")
dc = Location.create(name:"Washington DC USA")
charleston = Location.create(name:"Charleston SC USA")
ny = Location.create(name:"New York NY USA")
miami = Location.create(name: "Miami FL USA")
paris = Location.create(name:"Paris France")
london = Location.create(name:"London England")
rome = Location.create(name:"Rome Italy")
prague = Location.create(name:"Prague Czechoslovakia")
auckland = Location.create(name:"Auckland New Zealand")
leeds = Location.create(name:"Leeds England")
edinborough = Location.create(name:"Edinborough Scotland")
oahu = Location.create(name:"Oahu HI USA")
strassbourg = Location.create(name: "Strassbourg France")

food = Category.create(name:"Food")
housing = Category.create(name:"Housing")
transportation = Category.create(name:"Transportation")
shopping = Category.create(name:"Shopping")
activities = Category.create(name:"Activities")
misc = Category.create(name:"Miscellaneous")

trip = Trip.create(user: sarah, name: "Texas Vacation", budget: "100")
trip1 = Trip.create(user: nic, name: "Texas Paradise", budget: "1000")

whattaburger = Expense.create(cost:30.50, description:"Lunch at whattaburger", category: food, trip: trip, date: Time.now, location: houston)
rodeo = Expense.create(cost:112, description:"Rodeo night show", category: activities, trip: trip, date: Time.now, location: houston)
barn = Expense.create(cost:400, description:"Hotel stay at the Barn", category: housing, trip: trip, date: Time.now, location: austin)

sad_happy_masks = Expense.create(cost:44.99, description:"Sad face, happy face wall decor", category: shopping, trip: trip1, date: Time.now, location: houston)
improv_class = Expense.create(cost:432, description:"Week long improv class", category: activities, trip: trip1, date: Time.now, location: dallas)
mcdonalds = Expense.create(cost:12, description:"McDonalds dinner", category: food, trip: trip1, date: Time.now, location: dallas)
